name: Build

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
    name: Build and test with gradle

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
#      - name: Test with Gradle
#        run: ./gradlew test --no-daemon
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          path: build/libs/*.jar